; NOTE: Assertions have been autogenerated by utils/update_test_checks.py
; RUN: opt -S -passes=instcombine < %s | FileCheck %s --check-prefix=ENABLED
; RUN: opt -S -passes=instcombine -enable-multi-instr-patterns=false < %s | FileCheck %s --check-prefix=DISABLED

; Test that the -enable-multi-instr-patterns flag controls multi-instruction
; pattern matching in known bits analysis.

; Test 1: Inverted mask pattern (X & ~M) + (Y & M)
; With multi-instr patterns enabled, add is converted to disjoint or.
; With multi-instr patterns disabled, add remains add.
define i32 @test_inverted_mask(i32 noundef %x, i32 noundef %y, i32 noundef %m) {
; ENABLED-LABEL: @test_inverted_mask(
; ENABLED-NEXT:    [[X:%.*]] = xor i32 [[Y:%.*]], -1
; ENABLED-NEXT:    [[A:%.*]] = and i32 [[NOTM:%.*]], [[X]]
; ENABLED-NEXT:    [[B:%.*]] = and i32 [[M:%.*]], [[Y]]
; ENABLED-NEXT:    [[ADD:%.*]] = or disjoint i32 [[A]], [[B]]
; ENABLED-NEXT:    ret i32 [[ADD]]
;
; DISABLED-LABEL: @test_inverted_mask(
; DISABLED-NEXT:    [[X:%.*]] = xor i32 [[Y:%.*]], -1
; DISABLED-NEXT:    [[A:%.*]] = and i32 [[NOTM:%.*]], [[X]]
; DISABLED-NEXT:    [[B:%.*]] = and i32 [[M:%.*]], [[Y]]
; DISABLED-NEXT:    [[ADD:%.*]] = add i32 [[A]], [[B]]
; DISABLED-NEXT:    ret i32 [[ADD]]
;
  %notm = xor i32 %m, -1
  %a = and i32 %x, %notm
  %b = and i32 %y, %m
  %add = add i32 %a, %b
  ret i32 %add
}

; Test 2: X + (Y & ~X) pattern
; With multi-instr patterns enabled, add is converted to disjoint or.
; With multi-instr patterns disabled, add remains add.
define i32 @test_x_and_not_x(i32 noundef %x, i32 noundef %y) {
; ENABLED-LABEL: @test_x_and_not_x(
; ENABLED-NEXT:    [[ADD:%.*]] = or i32 [[X:%.*]], [[Y:%.*]]
; ENABLED-NEXT:    ret i32 [[ADD]]
;
; DISABLED-LABEL: @test_x_and_not_x(
; DISABLED-NEXT:    [[NOTX:%.*]] = xor i32 [[X:%.*]], -1
; DISABLED-NEXT:    [[MASKED:%.*]] = and i32 [[Y:%.*]], [[NOTX]]
; DISABLED-NEXT:    [[ADD:%.*]] = add i32 [[X]], [[MASKED]]
; DISABLED-NEXT:    ret i32 [[ADD]]
;
  %notx = xor i32 %x, -1
  %masked = and i32 %y, %notx
  %add = add i32 %x, %masked
  ret i32 %add
}

; Test 3: (A & B) + ~(A | B) pattern
; With multi-instr patterns enabled, add is converted to disjoint or.
; With multi-instr patterns disabled, add remains add.
define i32 @test_and_not_or(i32 noundef %a, i32 noundef %b) {
; ENABLED-LABEL: @test_and_not_or(
; ENABLED-NEXT:    [[OR:%.*]] = xor i32 [[A:%.*]], [[B:%.*]]
; ENABLED-NEXT:    [[NOTOR:%.*]] = xor i32 [[OR]], -1
; ENABLED-NEXT:    ret i32 [[NOTOR]]
;
; DISABLED-LABEL: @test_and_not_or(
; DISABLED-NEXT:    [[AND:%.*]] = and i32 [[A:%.*]], [[B:%.*]]
; DISABLED-NEXT:    [[OR:%.*]] = or i32 [[A]], [[B]]
; DISABLED-NEXT:    [[NOTOR:%.*]] = xor i32 [[OR]], -1
; DISABLED-NEXT:    [[ADD:%.*]] = add i32 [[AND]], [[NOTOR]]
; DISABLED-NEXT:    ret i32 [[ADD]]
;
  %and = and i32 %a, %b
  %or = or i32 %a, %b
  %notor = xor i32 %or, -1
  %add = add i32 %and, %notor
  ret i32 %add
}
